services:
  - type: web
    name: bot-mr-blocker
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GITLAB_TOKEN
        sync: false
      - key: GITLAB_URL
        value: https://gitlab.cs.ui.ac.id/api/v4
      - key: GITLAB_WEBHOOK_SECRET
        sync: false
      - key: JIRA_URL
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: JIRA_BLOCK_LINK_TYPE_NAME
        value: Blocks
      - key: REQUEST_TIMEOUT_SECONDS
        value: "10"
      - key: LOG_LEVEL
        value: INFO
