apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ppl-sihumas
nameSuffix: -production

resources:
  - ../../base

labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/instance: production
  - pairs:
      app.kubernetes.io/environment: production

patches:
  - path: ingress-patch.yaml
